baseURL = "https://akabob.netlify.app/"
languageCode = "en"
defaultContentLanguage = "en"
title = "aka bob"
theme = "KeepIt"

paginate = 12
enableEmoji = true
enableRobotsTXT = true

[menu]
  [[menu.main]]
    name = "Blog"
    url = "/posts/"
    weight = 1

  [[menu.main]]
    name = "Categories"
    url = "/categories/"
    weight = 2

  [[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 3

[params]
  author = "john mccormick"
  subtitle = "john mccormick"
  avatar = "https://cataas.com/cat/gif"

  [params.social]
    GitHub   = "johnmccormick99"
    Email    = "johnmccormick99@gmail.com"

  [params.share]
